[pytest]
markers =
    smoke: quick sanity checks
    navigation: tab/page navigation checks
    modal: subscribe popup behavior
    links: sidebar social/hyperlink checks
 
addopts = -v --html=reports/report.html --self-contained-html --alluredir=reports/allure-results --reruns 2 --reruns-delay 3